### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by jeffzhen** [SJ001/AI-Feynman#1]
Hi Silviu,

This is an exciting tool you have created! I'm a former PhD student of Max (graduated in 2016). I'm currently working for Waymo, and would love to try this out in my work, but I'm not sure if I should without any open source license mentioned here. Can you please include a license in the repo? An example MIT license: https://www.mit.edu/~amini/LICENSE.md.

Thank you!

Jeff

**Comment by SJ001** [comment]
Hello Jeff,

Greetings from Max! I am glad to hear you are interested in our code and sorry for the delay. I added a license. Please let me know if you encounter any further problems with the code.

**Comment by dcshapiro** [comment]
should be able to close this now...
