### ISSUE TITLE
Fortran filename changes

### ISSUE THREAD

**Issue by fastflair** [SJ001/AI-Feynman#19]
The compile.sh script in the feyman directory doesn't match the file names in the directory:
gfortran: error: symbolic_regress1.f: No such file or directory
gfortran: error: symbolic_regress2.f: No such file or directory
gfortran: error: symbolic_regress3.f: No such file or directory
symbolic_regress_mdl2.f:220: Error: Can't open included file 'tools.f'
symbolic_regress_mdl3.f:244: Error: Can't open included file 'tools.f'
chmod: cannot access 'brute_force_oneFile_v1.scr': No such file or directory
chmod: cannot access 'brute_force_oneFile_v2.scr': No such file or directory
chmod: cannot access 'brute_force_oneFile_v3.scr': No such file or directory

The .f files mentioned were renamed to .f90, also tools.f90  After renaming the files, these warnings occur:
symbolic_regress1.f:123:46:

      newloss = abs(xy(nvar+1,j) - f(n,ii,ops,xy(1,j)))
                                              1
Warning: Character length of actual argument shorter than of dummy argument ‘ops’ (60/256) at (1) [-Wargument-mismatch]
symbolic_regress1.f:133:55:

        rmsloss = rmsloss + (xy(nvar+1,j) - f(n,ii,ops,xy(1,j)))**2
                                                       1
Warning: Character length of actual argument shorter than of dummy argument ‘ops’ (60/256) at (1) [-Wargument-mismatch]
symbolic_regress_mdl2.f:108:63:

  call LoadMatrixTranspose(nvarmax+1,nvar+1,nmax,ndata,xy0,mysteryfile)
                                                               1
Warning: Character length of actual argument shorter than of dummy argument ‘f’ (60/256) at (1) [-Wargument-mismatch]
symbolic_regress_mdl2.f:148:42:

             offst = xy(nvar+1,j) - f(n,ii,ops,xy(1,j))
                                          1
Warning: Character length of actual argument shorter than of dummy argument ‘ops’ (60/256) at (1) [-Wargument-mismatch]
symbolic_regress_mdl2.f:171:50:

               newloss = abs(xy(nvar+1,j) - f(n,ii,ops,xy(1,j)) - bestoffset)
                                                  1
Warning: Character length of actual argument shorter than of dummy argument ‘ops’ (60/256) at (1) [-Wargument-mismatch]
symbolic_regress_mdl3.f:108:63:

  call LoadMatrixTranspose(nvarmax+1,nvar+1,nmax,ndata,xy0,mysteryfile)
                                                               1
Warning: Character length of actual argument shorter than of dummy argument ‘f’ (60/256) at (1) [-Wargument-mismatch]
symbolic_regress_mdl3.f:168:32:

             offst = y(j)/f(n,ii,ops,xy(1,j))
                                1
Warning: Character length of actual argument shorter than of dummy argument ‘ops’ (60/256) at (1) [-Wargument-mismatch]
symbolic_regress_mdl3.f:192:42:

               newloss = abs(y(j) - f(n,ii,ops,xy(1,j))*bestoffset)
                                          1
Warning: Character length of actual argument shorter than of dummy argument ‘ops’ (60/256) at (1) [-Wargument-mismatch]
chmod: cannot access 'brute_force_oneFile_v1.scr': No such file or directory
chmod: cannot access 'brute_force_oneFile_v2.scr': No such file or directory
chmod: cannot access 'brute_force_oneFile_v3.scr': No such file or directory

**Comment by dcshapiro** [comment]
Hi. To resolve the issue until the developers fix the code, I have updated the collab notebook that explains how to use the package, and set that code to use a previous commit in this repo. 

Code: https://github.com/dcshapiro/AI-Feynman/blob/master/AI_Feynman_2_0.ipynb
Article: https://towardsdatascience.com/ai-feynman-2-0-learning-regression-equations-from-data-3232151bd929#96e5
