### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by pone7** [SJ001/AI-Feynman#23]
Hi, when I run the example this error reported.

OSError                                   Traceback (most recent call last)
<ipython-input-356-23d96fc1fb7b> in <module>
      1 import aifeynman
      2 
----> 3 aifeynman.run_aifeynman("./example_data/", "example1.txt", 30, "14ops.txt", polyfit_deg=3, NN_epochs=500)

/opt/anaconda3/envs/climate/lib/python3.6/site-packages/aifeynman/S_run_aifeynman.py in run_aifeynman(pathdir, filename, BF_try_time, BF_ops_file_type, polyfit_deg, NN_epochs, vars_name, test_percentage)
    291     for j in range(len(PA_list)):
    292         PA = add_snap_expr_on_pareto(pathdir,filename,PA_list[j][-1],PA, "")
--> 293 
    294     PA_list = PA.get_pareto_points()
    295     np.savetxt("results/solution_first_snap_%s.txt" %filename,PA_list,fmt="%s")

/opt/anaconda3/envs/climate/lib/python3.6/site-packages/aifeynman/S_run_aifeynman.py in run_AI_all(pathdir, filename, BF_try_time, BF_ops_file_type, polyfit_deg, NN_epochs, PA)
    135                         sigma = new_sigma
    136                 except:
--> 137                     continue
    138         #except:
    139         #    idx_comp = 0

/opt/anaconda3/envs/climate/lib/python3.6/site-packages/numpy/lib/npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding, max_rows)
    979             fname = os_fspath(fname)
    980         if _is_string_like(fname):
--> 981             fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
    982             fencoding = getattr(fh, 'encoding', 'latin1')
    983             fh = iter(fh)

/opt/anaconda3/envs/climate/lib/python3.6/site-packages/numpy/lib/_datasource.py in open(path, mode, destpath, encoding, newline)
    267 
    268     ds = DataSource(destpath)
--> 269     return ds.open(path, mode, encoding=encoding, newline=newline)
    270 
    271 

/opt/anaconda3/envs/climate/lib/python3.6/site-packages/numpy/lib/_datasource.py in open(self, path, mode, encoding, newline)
    621                                       encoding=encoding, newline=newline)
    622         else:
--> 623             raise IOError("%s not found." % path)

OSError: results_comp.dat not found.

And I checked the code:

for qqqq in range(1):
    brute_force_comp("results/","gradients_comp_%s.txt" %filename,600,"14ops.txt")
    bf_all_output = np.loadtxt("results_comp.dat", dtype="str")

def brute_force_comp(pathdir, filename, BF_try_time, BF_ops_file_type, sigma=10, band=0):

    try_time = BF_try_time
    try_time_prefactor = BF_try_time
    file_type = BF_ops_file_type

    try:
        os.remove("results_comp.dat")
    except:
        pass

I am confused that why the results_comp.dat is removed before loading.

**Comment by youssefavx** [comment]
Hey @pone7  I'm getting this same error. Where did you find the code that includes the `os.remove"results_comp.dat`) ? I want to delete that to see if that fixes it.
