### ISSUE TITLE
facing Permission denied and Value error

### ISSUE THREAD

**Issue by K-PTL** [SJ001/AI-Feynman#3]
Hi Silviu, firstly I should say appreciate to you for such awesome code!
I'm engaged in R&D in company, and I wanna utilize this scripts; AI-Feynman.
I cloned this repository on 2020/04/21 and run the sample one;

`python ai_feynman_terminal_example.py --pathdir=../example_data/ --filename=example1.txt`

and I got 2 error messages.
1st, Permission denied as shown below:
```
Checking for brute force + 
14ops.txt: ./brute_force_oneFile_v3.scr: Permission denied
Checking for brute force * 
14ops.txt: ./brute_force_oneFile_v2.scr: Permission denied
Checking polyfit 
error
error
error
error
Complexity  RMSE  Expression
[0.0, 1.0, '0']
```

2nd, Value error after NN as shown below:
```
Checking for symmetry 
 example1.txt_train
Training a NN on the data... 

tensor(0.0162, grad_fn=<DivBackward0>)
tensor(0.0063, grad_fn=<DivBackward0>)
tensor(0.0139, grad_fn=<DivBackward0>)
tensor(0.0079, grad_fn=<DivBackward0>)
NN loss:  tensor(0.0079, grad_fn=<DivBackward0>) 

Torch not compiled with CUDA enabled
Traceback (most recent call last):
  File "/Users/~/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 973, in loadtxt
    fh = iter(fname)
TypeError: 'int' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ai_feynman_terminal_example.py", line 18, in <module>
    NN_epochs=opts.NN_epochs)
  File "/Users/~/gits/ai-feynman/Code/S_run_aifeynman.py", line 163, in run_aifeynman
    PA = run_AI_all(pathdir,filename+"_train",BF_try_time,BF_ops_file_type, polyfit_deg, NN_epochs)
  File "/Users/~/gits/ai-feynman/Code/S_run_aifeynman.py", line 113, in run_AI_all
    PA1 = run_AI_all(new_pathdir,new_filename,BF_try_time,BF_ops_file_type, polyfit_deg, NN_epochs, PA1_)
  File "/Users/~/gits/ai-feynman/Code/S_run_aifeynman.py", line 35, in run_AI_all
    data = np.loadtxt(pathdir+filename)
  File "/Users/~/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 976, in loadtxt
    raise ValueError('fname must be a string, file handle, or generator')
ValueError: fname must be a string, file handle, or generator
```

for the 1st error; permission denied, avoided by this change:
```python S_brute_force.py
def brute_force(~):
    if sep_type=="*":
-        subprocess.call(["./brute_force_oneFile_v2.scr", file_type, "%s" %try_time, pathdir+filename])
+        subprocess.call(["chmod u+x ./brute_force_oneFile_v2.scr", file_type, "%s" %try_time, pathdir+filename])
    if sep_type=="+":
-        subprocess.call(["./brute_force_oneFile_v3.scr", file_type, "%s" %try_time, pathdir+filename])
+        subprocess.call(["chmod u+x ./brute_force_oneFile_v3.scr", file_type, "%s" %try_time, pathdir+filename])
```

for the 2nd error; Value error, I checked inputed filename, I see the numerical value "-11" has received for this sentence.  
I have no idea how can I avoid this error....

My environment is:
- macOS Catalina 10.15.2
- Anaconda venv
- python=3.7.4

I hope this will be standard of 1st step of data analysis and progress moreover:)

**Comment by K-PTL** [comment]
@SJ001 
Hi Silviu, let me update this issue.
at first, I appreciate your creating `requirements.txt`, and I tried based on it.
I create python3.6 environment by Docker based on Ubuntu18.04.
I found missing libraries in your requirements.txt file shown as below;
(I got error messages of `ModuleNotFoundError`)
- scikit learn
- seaborn
- torch vision

and I installed them (from pypi by pip), totally I installed;
- joblib-0.14.1 scikit-learn-0.22.2.post1 sklearn-0.0
- seaborn-0.10.1
- pillow-7.1.2 torchvision-0.6.0

and I run sample one; python3 ai_feynman_terminal_example.py --pathdir=../example_data/ --filename=example1.txt

I got error permission denied error again.
I fixed it as below

> def brute_force(pathdir,filename,BF_try_time,BF_ops_file_type,sep_type="*"):
    try_time = BF_try_time
    try_time_prefactor = BF_try_time
    file_type = BF_ops_file_type
    try:
        os.remove("results.dat")
    except:
        pass
    if sep_type=="*":
-        subprocess.call(["./brute_force_oneFile_v2.scr", file_type, "%s" %try_time, pathdir+filename])
+        subprocess.call(["./brute_force_oneFile_v2.scr", file_type, "%s" %try_time, pathdir+filename], shell=True)
    if sep_type=="+":
-        subprocess.call(["./brute_force_oneFile_v3.scr", file_type, "%s" %try_time, pathdir+filename])
+        subprocess.call(["./brute_force_oneFile_v3.scr", file_type, "%s" %try_time, pathdir+filename], shell=True)

    return 1

but I can't run successfully....
I tried this software on Windows10, macOS Catalina, and Ubuntu, and failed all of them.
as issue#4, should I use NVIDIA GPU for this software??

**Comment by SJ001** [comment]
Hello!

Thank you for the message and your interest in our code and I am sorry for the late reply. The permission denied error should be fixed now (thank you for pointing it out). Also the NN issue should be fixed, too (please see issue#4 reply). I also removed some dependencies and in the current version sklearn, seaborn and torchvision are not needed anymore. Please let me know if you find other bugs or encounter any other issues (we are still adding features to the code, so things could easily break without us realizing immediately).

**Comment by K-PTL** [comment]
hello Silviu!
Thanks for your commitments to fix problems!
I made environment by Docker as below, and it's run completely with no error without GPU!!
- ubuntu (18.04.4 LTS (Bionic Beaver))
- python (3.6.9)
- GNU Fortran (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- libraries written in requirements.txt
- terminal commands; python3 ai_feynman_terminal_example.py --pathdir=../example_data/ --filename=example1.txt 

I fixed your code only 1 points, as pointed out firstly in this issue#3 because PERMISSION DENIED;
```python
def brute_force(~):
    if sep_type=="*":
-        subprocess.call(["./brute_force_oneFile_v2.scr", file_type, "%s" %try_time, pathdir+filename], shell=True)
+        subprocess.call(["chmod u+x ./brute_force_oneFile_v2.scr", file_type, "%s" %try_time, pathdir+filename], shell=True)
    if sep_type=="+":
-        subprocess.call(["./brute_force_oneFile_v3.scr", file_type, "%s" %try_time, pathdir+filename], shell=True)
+        subprocess.call(["chmod u+x ./brute_force_oneFile_v3.scr", file_type, "%s" %try_time, pathdir+filename], shell=True)
```

I appreciate to use this AI, thank you so much!!! ;)
I hope the day comes we can use only by `from aifeynman import AI_Feynman as af`, for example.

**Comment by SJ001** [comment]
Glad to hear it is working now! I actually added a few more lines in the compile.sh that should have fixed the permission denied problem. Do you still get the permission denied error after running ./compile?
We are working on making the code pip installable, hopefully it will be done soon. Meanwhile we are adding new functionalities so please let me know if something stops working properly.

**Comment by douglasquincyadams** [comment]
I am running into very similar issue. 
For me I got file not found issue for the .scr files:

FileNotFoundError: [Errno 2] No such file or directory: './brute_force_oneFile_v3.scr': './brute_force_oneFile_v3.scr'

I suspect its the same issue.
