### ISSUE TITLE
Windows 10/64bits DLL error

### ISSUE THREAD

**Issue by caxelrud** [SJ001/AI-Feynman#31]
Hi,
When testing the example1 in my Windows 10/64bits computer I got the following error:
```
File "C:\Users\inter\AppData\Local\Continuum\anaconda3\Scripts\feynman_sr_mdl_mult.exe\__main__.py", line 4, in <module>
ImportError: DLL load failed: %1 is not a valid Win32 application.

```

**Comment by kumarUjjawal** [comment]
You could download, extract and move the DLL file from [here](https://www.dll-files.com/) to your anaconda3\Library\bin folder and see if it helps.
