### ISSUE TITLE
Win Installation Error

### ISSUE THREAD

**Issue by martaSznil** [SJ001/AI-Feynman#34]
when running pip install aifeynman I am getting this error:

```
    building 'aifeynman._symbolic_regress1' extension
    error: extension 'aifeynman._symbolic_regress1' has Fortran sources but no Fortran compiler found
```
I checked here for a solution:
`https://stackoverflow.com/questions/36250303/fortran-sources-but-no-fortran-compiler-found`
I installed Cygwin, but I was not sure how to "add the path to its binary to the system PATH". Where do I find the binary? Anyway, I added the whole cygwin directory and cygwin\bin to PATH but that didn't work. Then I tried to install MinGW but this only gives me a zip file with stuff in it that I don't know how to deal with. What do I have to do? Thanks.

**Comment by martaSznil** [comment]
Can anyone advise on this?

**Comment by lawliet357** [comment]
Hi, the author has description in the instruction:
Note that for now, AI Feynman is supported only for **Linux** and **Mac** environments.

**Comment by jresch** [comment]
Before installing AIFeynman, try "sudo apt-get install gfortran"
Worked for me, and I got the same error
