### ISSUE TITLE
"...dh key too small" error 

### ISSUE THREAD

**Issue by hoangquevn** [SJ001/AI-Feynman#38]
I get in trouble when trying the line "aifeynman.get_demos('example_data')". I'm using Ubuntu 20.04 and Python 3.8.5. I've tried by lowering security level in /etc/ssl/openssl.cnf file. But the wise men said that I should contact the administrator of the service  instead of trying to change seclevel. Please help me to fix this error. Thank you!

**Comment by tinaxia2016** [comment]
I came across the same issue. How did you solve the problem? Any suggestions will be helpful, thanks in advance.

**Comment by xlucn** [comment]
Or just download the files from GitHub, they are in `example_data` folder
