### ISSUE TITLE
Hard to get correct results for a simple custom case `sine(2pi*10*x0) * x0` 

### ISSUE THREAD

**Issue by leoniloris** [SJ001/AI-Feynman#69]
I'm trying to run a simbolic regression for:
```python
np.sin(2*np.pi*10*x0) * x0
```
which should yield a plot like this:
![image](https://user-images.githubusercontent.com/22769167/179843446-baa7afbd-b26b-488c-942a-76584c1f2101.png)

but I just can't get any useful results that remotely looks like the equation.
Code to reproduce:

```python
import aifeynman
import numpy as np

DATA_FOLDER = "./data1/"
DATA_FILE = "am_fm1"

# build data
x0 = np.arange(0, 1, 0.0001)
y = np.sin(2*np.pi*10*x0) * x0

# save data
data = np.array([x0, y]).T
np.savetxt(f"{DATA_FOLDER}/{DATA_FILE}", data)

aifeynman.run_aifeynman(DATA_FOLDER, DATA_FILE, 60, "14ops.txt", polyfit_deg=1, NN_epochs=300)
```

**Comment by AndreScaffidi** [comment]
Hi, What was the issue in the end? I'm having a similar issue.
