### ISSUE TITLE
Reproduce results on problems from McDermott et al. [GECCO 2012]

### ISSUE THREAD

**Issue by neighthan** [SJ001/AI-Feynman#8]
In the paper, you note another benchmark suite that you used, from your reference 41. How would one reproduce those results using this repo?

**Comment by SJ001** [comment]
Hello! All that is needed is to create a file (ideally .txt) in which the first n-1 columns are the independent variables while the last one is the dependent variable, for each of the functions presented in McDermott et al. (I used numpy.savetxt() for that). After that our code can be called, for example, using python ai_feynman_example.py, in which the first 2 parameters ("../example_data/", "example2.txt") should be replaced with the pathdir and filename of the file you created. Please let me know if you have more questions.
