### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by dcshapiro** [SJ001/AI-Feynman#9]
I'm using the python interface:

e.g.: *run_aifeynman(path,file,30,"7ops.txt", polyfit_deg=3, NN_epochs=600)*

During the execution, I see the following message in the output:
**Checking for brute force + 
set: Syntax Error.**

and then the solver progresses as if there is no error. For example, the message is followed by:

**Complexity  RMSE  Expression
[51.36772134865003, 26.867787072542978, '0.26903028974544*x2 + 3']
[102.82317913962802, 25.759757319218686, '-0.266777978995514*x0 + 0.26903028974544*x2 + 3']
[200.04861120822196, 24.01782206148508, '-0.266777978995514*x0 - 0.264791621935148*x1 + 0.26903028974544*x2 + 0.26547944179182*x3 + 3']
Checking for brute force + 

Trying to solve mysteries with brute force...
Trying to solve results/mystery_world_atan/duplicateVarsWithNoise.txt_train...
/bin/cp -p results/mystery_world_atan/duplicateVarsWithNoise.txt_train mystery.dat**

Is this "set: Syntax Error" a real problem or is everything fine?

Thanks.

**Comment by SJ001** [comment]
Hello! I haven't encountered this error before, but I think it comes from the .scr files (it is there where "set" is called). Given the error and the output so far, I assume that the brute force function is not called at all, so a big part of the possible output is lost, so that is something that definitely needs to be fixed. However it seems to be an environment issue. What machine are you running the code on?

**Comment by dcshapiro** [comment]
Hi Silviu. Thanks for the reply. I am writing a medium article on how to use the library. Happy to discuss further. you can reach me at daniel a_t lemay.ai

Here is the full notebook I am using to evaluate the library, including the **set: Syntax Error** message: https://github.com/dcshapiro/AI-Feynman/blob/master/AI_Feynman.ipynb

It would be great to understand if I missed anything.

**Comment by dcshapiro** [comment]
Oh FYI I am running the notebook in Google Collab so that others can avoid any config issues

**Comment by dcshapiro** [comment]
I think you can close this now :o)

**Comment by dcshapiro** [comment]
Thx. Wonderful.
